ALTER TABLE users ADD COLUMN last_daily_quest_claim DATE DEFAULT NULL;
ALTER TABLE users ADD COLUMN last_monthly_quest_claim DATE DEFAULT NULL;
ALTER TABLE chapters ADD COLUMN completed_at DATETIME DEFAULT NULL;
ALTER TABLE questions ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;