-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.4.3 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for interviewai
CREATE DATABASE IF NOT EXISTS `interviewai` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `interviewai`;

-- Dumping structure for table interviewai.chapters
CREATE TABLE IF NOT EXISTS `chapters` (
  `id` int NOT NULL AUTO_INCREMENT,
  `course_id` int NOT NULL,
  `chapter_number` int DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  PRIMARY KEY (`id`),
  KEY `course_id` (`course_id`),
  CONSTRAINT `chapters_ibfk_1` FOREIGN KEY (`course_id`) REFERENCES `generated_courses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table interviewai.chapters: ~0 rows (approximately)
DELETE FROM `chapters`;
INSERT INTO `chapters` (`id`, `course_id`, `chapter_number`, `name`, `description`) VALUES
	(1, 3, 1, 'Java Fundamentals & OOP Principles', 'Review of core Java concepts, including data types, operators, control flow, and object-oriented programming principles like encapsulation, inheritance, polymorphism, and abstraction.'),
	(2, 3, 2, 'Collections & Data Structures', 'Focuses on understanding and using Java Collections Framework, including lists, sets, maps, and queues. Covers choosing the right data structure for a given problem and understanding time complexity.'),
	(3, 3, 3, 'Exception Handling & Multithreading', 'Covers exception handling mechanisms in Java (try-catch-finally) and fundamental concepts of multithreading, including creating and managing threads, synchronization, and common concurrency issues.'),
	(4, 3, 4, 'Common Java APIs & Design Patterns', 'Quick review of important Java APIs like I/O, Networking, and basic understanding of common design patterns, such as Singleton, Factory, and Observer.'),
	(5, 3, 5, 'JVM Internals and Garbage Collection', 'A brief review of the Java Virtual Machine architecture and how garbage collection works.'),
	(6, 4, 1, 'C++ Fundamentals & Memory Management', 'Review core C++ concepts crucial for game development, including pointers, memory allocation, and object-oriented principles. Focus on best practices for avoiding memory leaks and ensuring efficient code.'),
	(7, 4, 2, 'Game Engine Architecture & Design Patterns', 'Covers fundamental game engine concepts like game loops, scene management, rendering pipelines, and commonly used design patterns in game development. Review the Model-View-Controller (MVC) and Observer patterns.'),
	(8, 4, 3, 'Linear Algebra & Game Math', 'Review vector operations, matrices, transformations, and other mathematical concepts commonly used in game development for physics, rendering, and AI.'),
	(9, 4, 4, 'Data Structures and Algorithms', 'Covers essential data structures like arrays, linked lists, trees, and hash tables, along with fundamental algorithms for searching, sorting, and pathfinding (e.g., A*).'),
	(10, 4, 5, 'C++ Specific Game Dev Libraries and Concepts', 'This chapter will focus on concepts commonly found in game development settings with C++. It will explore common libraries and how these can be used in game dev.'),
	(11, 5, 1, 'JavaScript Fundamentals & Asynchronous Programming', 'Review core JavaScript concepts, including data types, control flow, DOM manipulation, and especially asynchronous JavaScript with Promises and Async/Await.  Focus on understanding how to write efficient and maintainable JavaScript code.'),
	(12, 5, 2, 'Frontend Frameworks (React)', 'Focus on React fundamentals: components, JSX, state management, lifecycle methods (or hooks for functional components), and event handling.  Be prepared to discuss React best practices and common patterns.'),
	(13, 5, 3, 'Backend Fundamentals (Node.js & Express)', 'Focus on Node.js runtime, Express.js framework for building APIs, routing, middleware, and basic database interactions. Understanding of RESTful API design is critical.'),
	(14, 5, 4, 'Databases (SQL & NoSQL)', 'Review the differences between SQL (e.g., PostgreSQL, MySQL) and NoSQL (e.g., MongoDB) databases.  Understand basic CRUD operations, querying, and data modeling concepts.'),
	(15, 5, 5, 'System Design & Architecture (Basic Principles)', 'Understand basic architectural patterns, scalability concepts (horizontal vs. vertical), load balancing, caching, and common system design tradeoffs. Focus on communicating your design thinking process.'),
	(16, 6, 1, 'JavaScript Fundamentals & DOM Manipulation', 'This chapter covers core JavaScript concepts and how to interact with the Document Object Model (DOM). Expect questions on data types, closures, asynchronous programming, and DOM manipulation techniques.'),
	(17, 6, 2, 'React.js Fundamentals', 'This chapter focuses on React.js basics, including components, JSX, state management (using useState and useEffect), props, and handling events.  Also, understanding of component lifecycle.'),
	(18, 6, 3, 'Node.js & Express.js', 'This chapter tests your knowledge of Node.js and the Express.js framework.  Expect questions on routing, middleware, handling requests and responses, and database interactions.'),
	(19, 6, 4, 'Databases & APIs', 'This chapter covers database concepts (SQL & NoSQL), RESTful API design, and interacting with databases from your backend (Node.js).'),
	(20, 7, 1, 'فهم الغرض من التأشيرة والبرنامج الدراسي', 'في هذا الفصل، سنركز على التأكد من فهمك الكامل لغرض تأشيرة الطالب، والبرنامج الدراسي الذي اخترته، وكيف يتماشى مع أهدافك الأكاديمية والمهنية.'),
	(21, 7, 2, 'الإلمام بالوضع المالي والقدرة على تحمل التكاليف', 'في هذا الفصل، سنتأكد من أنك تفهم تماماً كيفية تمويل دراستك وإقامتك في الخارج، وأن لديك دليل قاطع على قدرتك المالية.'),
	(22, 7, 3, 'الارتباط ببلدك الأم والنية في العودة', 'في هذا الفصل، سنركز على إظهار ارتباطك القوي ببلدك الأم والنية الصادقة في العودة بعد الانتهاء من دراستك.'),
	(23, 7, 4, 'أسئلة المقابلة الشائعة والإجابات المثالية', 'في هذا الفصل، سنستعرض مجموعة من أسئلة المقابلة الشائعة ونقدم لك نماذج للإجابات المثالية التي يمكنك استخدامها كنقطة انطلاق.');

-- Dumping structure for table interviewai.choices
CREATE TABLE IF NOT EXISTS `choices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `question_id` int NOT NULL,
  `choice_text` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `question_id` (`question_id`),
  CONSTRAINT `choices_ibfk_1` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=445 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table interviewai.choices: ~0 rows (approximately)
DELETE FROM `choices`;
INSERT INTO `choices` (`id`, `question_id`, `choice_text`) VALUES
	(1, 1, 'A. Encapsulation'),
	(2, 1, 'B. Polymorphism'),
	(3, 1, 'C. Compilation'),
	(4, 1, 'D. Inheritance'),
	(5, 2, 'A. It makes the class abstract'),
	(6, 2, 'B. It prevents the class from being instantiated'),
	(7, 2, 'C. It prevents the class from being subclassed'),
	(8, 2, 'D. It makes all methods in the class final'),
	(9, 3, 'A. MyClass.new()'),
	(10, 3, 'B. create MyClass()'),
	(11, 3, 'C. new MyClass()'),
	(12, 3, 'D. MyClass()'),
	(13, 4, 'A. \'==\' compares object content, while \'.equals()\' compares memory addresses'),
	(14, 4, 'B. \'==\' compares memory addresses, while \'.equals()\' compares object content (default behavior)'),
	(15, 4, 'C. Both \'==\' and \'.equals()\' always compare memory addresses'),
	(16, 4, 'D. Both \'==\' and \'.equals()\' always compare object content'),
	(17, 5, 'A. To make a variable immutable'),
	(18, 5, 'B. To create a singleton instance'),
	(19, 5, 'C. To associate a variable or method with the class rather than an instance of the class'),
	(20, 5, 'D. To create an abstract method'),
	(21, 6, 'A. Queue'),
	(22, 6, 'B. Set'),
	(23, 6, 'C. Stack'),
	(24, 6, 'D. List'),
	(25, 7, 'A. List'),
	(26, 7, 'B. Set'),
	(27, 7, 'C. Map'),
	(28, 7, 'D. Queue'),
	(29, 8, 'A. LinkedList'),
	(30, 8, 'B. ArrayList'),
	(31, 8, 'C. Vector'),
	(32, 8, 'D. Stack'),
	(33, 9, 'A. To generate a unique identifier for an object'),
	(34, 9, 'B. To convert an object to a String representation'),
	(35, 9, 'C. To provide a hash code value for an object, which is used by hash-based collections like HashMap and HashSet'),
	(36, 9, 'D. To compare two objects for equality'),
	(37, 10, 'A. HashSet'),
	(38, 10, 'B. TreeSet'),
	(39, 10, 'C. LinkedHashSet'),
	(40, 10, 'D. PriorityQueue'),
	(41, 11, 'A. catch'),
	(42, 11, 'B. finally'),
	(43, 11, 'C. throw'),
	(44, 11, 'D. throws'),
	(45, 12, 'A. To handle exceptions that were not caught by any catch block'),
	(46, 12, 'B. To execute code only if an exception occurs'),
	(47, 12, 'C. To execute code regardless of whether an exception occurs or not'),
	(48, 12, 'D. To define the type of exception that can be caught'),
	(49, 13, 'A. Running'),
	(50, 13, 'B. Blocked'),
	(51, 13, 'C. Ready'),
	(52, 13, 'D. Compiled'),
	(53, 14, 'A. To prevent memory leaks'),
	(54, 14, 'B. To ensure that only one thread can access a specific block of code or method at a time'),
	(55, 14, 'C. To create a new thread'),
	(56, 14, 'D. To suspend a thread\'s execution'),
	(57, 15, 'A. A situation where a thread is terminated unexpectedly'),
	(58, 15, 'B. A situation where two or more threads are blocked indefinitely, waiting for each other to release resources'),
	(59, 15, 'C. A situation where a thread consumes excessive CPU resources'),
	(60, 15, 'D. A situation where a thread experiences a runtime exception'),
	(61, 16, 'A. FileInputStream'),
	(62, 16, 'B. ObjectInputStream'),
	(63, 16, 'C. BufferedReader'),
	(64, 16, 'D. DataInputStream'),
	(65, 17, 'A. Factory'),
	(66, 17, 'B. Singleton'),
	(67, 17, 'C. Observer'),
	(68, 17, 'D. Strategy'),
	(69, 18, 'A. ServerSocket'),
	(70, 18, 'B. Socket'),
	(71, 18, 'C. DatagramSocket'),
	(72, 18, 'D. URL'),
	(73, 19, 'A. To define a one-to-many dependency between objects'),
	(74, 19, 'B. To encapsulate object creation logic'),
	(75, 19, 'C. To ensure only one instance of a class is created'),
	(76, 19, 'D. To define a family of algorithms, encapsulate each one, and make them interchangeable'),
	(77, 20, 'A. InputStream'),
	(78, 20, 'B. Reader'),
	(79, 20, 'C. OutputStream'),
	(80, 20, 'D. Writer'),
	(81, 21, 'A. Stack'),
	(82, 21, 'B. Heap'),
	(83, 21, 'C. Method Area'),
	(84, 21, 'D. Native Method Stack'),
	(85, 22, 'A. To optimize the execution speed of the JVM'),
	(86, 22, 'B. To reclaim memory occupied by unused objects'),
	(87, 22, 'C. To prevent stack overflow errors'),
	(88, 22, 'D. To manage thread synchronization'),
	(89, 23, 'A. Old Generation'),
	(90, 23, 'B. Permanent Generation (PermGen/Metaspace)'),
	(91, 23, 'C. Young Generation'),
	(92, 23, 'D. Code Cache'),
	(93, 24, 'A. Serial Garbage Collector'),
	(94, 24, 'B. Parallel Garbage Collector'),
	(95, 24, 'C. Concurrent Mark Sweep (CMS) Garbage Collector'),
	(96, 24, 'D. Quantum Garbage Collector'),
	(97, 25, 'A. To initialize an object\'s state'),
	(98, 25, 'B. To release resources held by an object before it\'s garbage collected'),
	(99, 25, 'C. To create a new object instance'),
	(100, 25, 'D. To specify the object\'s equality criteria'),
	(101, 26, 'A. int arr[10] = new int;'),
	(102, 26, 'B. int* arr = new int[10];'),
	(103, 26, 'C. int arr = new int[10];'),
	(104, 26, 'D. int* arr = malloc(10 * sizeof(int));'),
	(105, 27, 'A. A pointer that automatically increments when used; helps avoid infinite loops.'),
	(106, 27, 'B. A pointer that automatically tracks memory usage and prevents performance bottlenecks.'),
	(107, 27, 'C. A pointer that automatically manages the lifetime of dynamically allocated objects, preventing memory leaks.'),
	(108, 27, 'D. A pointer that automatically optimizes code execution for faster performance.'),
	(109, 28, 'A. Inheritance'),
	(110, 28, 'B. Polymorphism'),
	(111, 28, 'C. Encapsulation'),
	(112, 28, 'D. Recursion'),
	(113, 29, 'A. To declare a variable that can only be assigned a value once.'),
	(114, 29, 'B. To declare a variable that is stored in constant memory.'),
	(115, 29, 'C. To indicate that a variable or function parameter cannot be modified.'),
	(116, 29, 'D. To declare a variable with a fixed size.'),
	(117, 30, 'A. \'malloc\' allocates memory and initializes it, while \'new\' only allocates memory.'),
	(118, 30, 'B. \'new\' allocates memory and calls the constructor of the object, while \'malloc\' only allocates raw memory.'),
	(119, 30, 'C. \'malloc\' is type-safe, while \'new\' is not.'),
	(120, 30, 'D. \'new\' is used for primitive types, while \'malloc\' is used for objects.'),
	(121, 31, 'A. To handle user input.'),
	(122, 31, 'B. To render the game graphics.'),
	(123, 31, 'C. To update the game state and render the graphics repeatedly.'),
	(124, 31, 'D. To load game assets.'),
	(125, 32, 'A. Singleton'),
	(126, 32, 'B. Observer'),
	(127, 32, 'C. Factory'),
	(128, 32, 'D. Model-View-Controller (MVC)'),
	(129, 33, 'A. A graph representing the levels in a game.'),
	(130, 33, 'B. A hierarchical data structure representing the spatial relationships between game objects in a scene.'),
	(131, 33, 'C. A graph showing the dependencies between different game scripts.'),
	(132, 33, 'D. A graph visualizing the player\'s progress through the game.'),
	(133, 34, 'A. To load game assets.'),
	(134, 34, 'B. To handle user input.'),
	(135, 34, 'C. To perform calculations on vertices and pixels to determine the final rendered image.'),
	(136, 34, 'D. To manage game physics.'),
	(137, 35, 'A. Singleton'),
	(138, 35, 'B. Observer'),
	(139, 35, 'C. Factory'),
	(140, 35, 'D. Decorator'),
	(141, 36, 'A. To calculate the angle between two vectors.'),
	(142, 36, 'B. To calculate the length of a vector.'),
	(143, 36, 'C. To calculate a vector perpendicular to two other vectors.'),
	(144, 36, 'D. To calculate the component of one vector in the direction of another.'),
	(145, 37, 'A. Translation matrix'),
	(146, 37, 'B. Scaling matrix'),
	(147, 37, 'C. Rotation matrix'),
	(148, 37, 'D. Orthographic Projection Matrix'),
	(149, 38, 'A. A type of integer used for representing game scores.'),
	(150, 38, 'B. A four-dimensional number system used to represent rotations, avoiding gimbal lock.'),
	(151, 38, 'C. A type of string used to store player names.'),
	(152, 38, 'D. A data structure used to represent 3D models.'),
	(153, 39, 'A. A scalar value representing the area of the parallelogram formed by the vectors.'),
	(154, 39, 'B. A vector perpendicular to both input vectors.'),
	(155, 39, 'C. A vector pointing in the same direction as the first input vector.'),
	(156, 39, 'D. A scalar value representing the angle between the two vectors.'),
	(157, 40, 'A. To store the color of a game object.'),
	(158, 40, 'B. To store the textures of a game object.'),
	(159, 40, 'C. To represent the position, rotation, and scale of a game object in world space.'),
	(160, 40, 'D. To calculate the physics of a game object.'),
	(161, 41, 'A. Linked List'),
	(162, 41, 'B. Binary Search Tree'),
	(163, 41, 'C. Hash Table'),
	(164, 41, 'D. Sorted Array'),
	(165, 42, 'A. Bubble Sort'),
	(166, 42, 'B. Insertion Sort'),
	(167, 42, 'C. Merge Sort'),
	(168, 42, 'D. Selection Sort'),
	(169, 43, 'A. Sorting data'),
	(170, 43, 'B. Pathfinding'),
	(171, 43, 'C. Data compression'),
	(172, 43, 'D. Memory management'),
	(173, 44, 'A. O(n)'),
	(174, 44, 'B. O(log n)'),
	(175, 44, 'C. O(1)'),
	(176, 44, 'D. O(n log n)'),
	(177, 45, 'A. Queue'),
	(178, 45, 'B. Linked List'),
	(179, 45, 'C. Stack'),
	(180, 45, 'D. Heap'),
	(181, 46, 'A. OpenGL'),
	(182, 46, 'B. STL (Standard Template Library)'),
	(183, 46, 'C. Qt'),
	(184, 46, 'D. Boost'),
	(185, 47, 'A. To manage memory allocation.'),
	(186, 47, 'B. To organize game entities and their data in a modular and flexible way.'),
	(187, 47, 'C. To handle user input.'),
	(188, 47, 'D. To render game graphics.'),
	(189, 48, 'A. Immediate mode GUIs are faster, while retained mode GUIs are easier to use.'),
	(190, 48, 'B. Retained mode GUIs are rendered only once and persist on screen, while immediate mode GUIs are re-rendered every frame.'),
	(191, 48, 'C. Immediate mode GUIs are only suitable for simple games.'),
	(192, 48, 'D. The terms are interchangeable and have the same meaning.'),
	(193, 49, 'A. Inheritance'),
	(194, 49, 'B. Polymorphism'),
	(195, 49, 'C. Templates'),
	(196, 49, 'D. Encapsulation'),
	(197, 50, 'A. To automatically fix bugs in the code.'),
	(198, 50, 'B. To optimize the game\'s graphics.'),
	(199, 50, 'C. To identify performance bottlenecks and areas where the code can be optimized.'),
	(200, 50, 'D. To create level designs automatically.'),
	(201, 51, 'A: variable myConst = 10;'),
	(202, 51, 'B: const myConst = 10;'),
	(203, 51, 'C: let myConst = 10;'),
	(204, 51, 'D: define myConst = 10;'),
	(205, 52, 'A: To prevent a function from being executed.'),
	(206, 52, 'B: To automatically handle all errors in a function.'),
	(207, 52, 'C: To make a function return a Promise.'),
	(208, 52, 'D: To make a function run synchronously.'),
	(209, 53, 'A: array.add()'),
	(210, 53, 'B: array.push()'),
	(211, 53, 'C: array.append()'),
	(212, 53, 'D: array.insert()'),
	(213, 54, 'A: `==` compares values and types, `===` compares only values.'),
	(214, 54, 'B: `==` compares only values, `===` compares values and types.'),
	(215, 54, 'C: `==` is used for assignment, `===` is used for comparison.'),
	(216, 54, 'D: There is no difference, they are interchangeable.'),
	(217, 55, 'A: `promise.catchError(error => { ... });`'),
	(218, 55, 'B: `promise.error(error => { ... });`'),
	(219, 55, 'C: `promise.then(null, error => { ... });`'),
	(220, 55, 'D: All of the above.'),
	(221, 56, 'A: A templating engine.'),
	(222, 56, 'B: A JavaScript extension that allows writing HTML-like syntax in JavaScript.'),
	(223, 56, 'C: A CSS preprocessor.'),
	(224, 56, 'D: A state management library.'),
	(225, 57, 'A: `this.state.name = \'New Name\';`'),
	(226, 57, 'B: `setState({ name: \'New Name\' });`'),
	(227, 57, 'C: `this.setState({ name: \'New Name\' });`'),
	(228, 57, 'D: `this.updateState({ name: \'New Name\' });`'),
	(229, 58, 'A: A way to add styling to React components.'),
	(230, 58, 'B: A way to use state and other React features in functional components.'),
	(231, 58, 'C: A way to handle events in React components.'),
	(232, 58, 'D: A replacement for class components.'),
	(233, 59, 'A: To create side effects in functional components.'),
	(234, 59, 'B: To update the state of a component.'),
	(235, 59, 'C: To render the component.'),
	(236, 59, 'D: To define the component\'s template.'),
	(237, 60, 'A: To style list items.'),
	(238, 60, 'B: To uniquely identify list items, improving performance and preventing unexpected behavior.'),
	(239, 60, 'C: To sort the list items.'),
	(240, 60, 'D: To filter the list items.'),
	(241, 61, 'A: A JavaScript library.'),
	(242, 61, 'B: A JavaScript runtime environment that executes JavaScript code outside of a web browser.'),
	(243, 61, 'C: A database management system.'),
	(244, 61, 'D: A web browser.'),
	(245, 62, 'A: A JavaScript library for creating user interfaces.'),
	(246, 62, 'B: A Node.js web application framework that provides a robust set of features for web and mobile applications.'),
	(247, 62, 'C: A database management system.'),
	(248, 62, 'D: A package manager for Node.js.'),
	(249, 63, 'A: A function that handles routing in an Express application.'),
	(250, 63, 'B: A function that has access to the request object (req), the response object (res), and the next middleware function in the application’s request-response cycle.'),
	(251, 63, 'C: A function that renders HTML templates.'),
	(252, 63, 'D: A function that connects to a database.'),
	(253, 64, 'A: POST'),
	(254, 64, 'B: PUT'),
	(255, 64, 'C: DELETE'),
	(256, 64, 'D: GET'),
	(257, 65, 'A: Representational State Transfer'),
	(258, 65, 'B: Resource Exchange Transfer'),
	(259, 65, 'C: Relational State Technology'),
	(260, 65, 'D: Reactive State Transmission'),
	(261, 66, 'A: MySQL'),
	(262, 66, 'B: PostgreSQL'),
	(263, 66, 'C: MongoDB'),
	(264, 66, 'D: SQLite'),
	(265, 67, 'A: INSERT'),
	(266, 67, 'B: UPDATE'),
	(267, 67, 'C: DELETE'),
	(268, 67, 'D: SELECT'),
	(269, 68, 'A: To convert data between incompatible type systems in relational databases.'),
	(270, 68, 'B: To provide a way to interact with a database using object-oriented programming concepts.'),
	(271, 68, 'C: To optimize database query performance.'),
	(272, 68, 'D: To encrypt database connections.'),
	(273, 69, 'A: Create, Read, Update, Delete'),
	(274, 69, 'B: Connect, Retrieve, Update, Deploy'),
	(275, 69, 'C: Compile, Run, Update, Debug'),
	(276, 69, 'D: Capture, Read, Undo, Download'),
	(277, 70, 'A: Schema-less data structure'),
	(278, 70, 'B: Data is stored in documents'),
	(279, 70, 'C: Data is organized into tables with rows and columns'),
	(280, 70, 'D: High scalability for unstructured data'),
	(281, 71, 'A: Increasing the resources (CPU, RAM) of a single server.'),
	(282, 71, 'B: Adding more servers to a system.'),
	(283, 71, 'C: Optimizing database queries.'),
	(284, 71, 'D: Improving network bandwidth.'),
	(285, 72, 'A: To protect a server from DDoS attacks.'),
	(286, 72, 'B: To distribute network traffic across multiple servers.'),
	(287, 72, 'C: To optimize database performance.'),
	(288, 72, 'D: To encrypt network communication.'),
	(289, 73, 'A: Storing frequently accessed data in a faster storage medium.'),
	(290, 73, 'B: Encrypting data before storing it.'),
	(291, 73, 'C: Backing up data to prevent data loss.'),
	(292, 73, 'D: Compressing data to save storage space.'),
	(293, 74, 'A: Easier to debug and maintain a monolithic codebase.'),
	(294, 74, 'B: Faster development cycles and independent deployments.'),
	(295, 74, 'C: Tighter coupling between different parts of the application.'),
	(296, 74, 'D: Single point of failure for the entire application.'),
	(297, 75, 'A: A theorem about the relationship between Consistency, Availability, and Partition Tolerance in distributed systems.'),
	(298, 75, 'B: A theorem about the maximum number of concurrent users a system can handle.'),
	(299, 75, 'C: A theorem about the cost of developing a distributed system.'),
	(300, 75, 'D: A theorem about the security of a distributed system.'),
	(301, 76, 'A: `==` compares values, `===` compares values and types.'),
	(302, 76, 'B: `==` compares types, `===` compares values.'),
	(303, 76, 'C: `==` always returns true, `===` returns false.'),
	(304, 76, 'D: There is no difference between them.'),
	(305, 77, 'A: A function that has access to the parent scope, even after the parent function has closed.'),
	(306, 77, 'B: A type of loop.'),
	(307, 77, 'C: A way to declare variables globally.'),
	(308, 77, 'D: A function that calls itself recursively.'),
	(309, 78, 'A: Use the `preventDefault()` method on the event object.'),
	(310, 78, 'B: Set `event.default` to false.'),
	(311, 78, 'C: Call `stopEvent()` on the element.'),
	(312, 78, 'D: Remove the event listener.'),
	(313, 79, 'A: The process of an event being triggered on a parent element before its child elements.'),
	(314, 79, 'B: The process of an event being triggered on an element and then propagating up the DOM tree to its parent elements.'),
	(315, 79, 'C: The process of an event being triggered on all elements simultaneously.'),
	(316, 79, 'D: The process of an event being prevented from triggering on any element.'),
	(317, 80, 'A: Number'),
	(318, 80, 'B: String'),
	(319, 80, 'C: Boolean'),
	(320, 80, 'D: Float'),
	(321, 81, 'A: A JavaScript extension that allows writing HTML-like syntax in JavaScript.'),
	(322, 81, 'B: A special type of component.'),
	(323, 81, 'C: A build tool for React applications.'),
	(324, 81, 'D: A new version of JavaScript.'),
	(325, 82, 'A: To manage the state of a functional component.'),
	(326, 82, 'B: To handle side effects in a functional component.'),
	(327, 82, 'C: To create a new component.'),
	(328, 82, 'D: To import external libraries.'),
	(329, 83, 'A: Using `props`.'),
	(330, 83, 'B: Using `state`.'),
	(331, 83, 'C: Using `refs`.'),
	(332, 83, 'D: Using `context`.'),
	(333, 84, 'A: It performs side effects in functional components, like data fetching or DOM manipulation.'),
	(334, 84, 'B: It manages the component\'s state.'),
	(335, 84, 'C: It defines the component\'s UI.'),
	(336, 84, 'D: It handles user events.'),
	(337, 85, 'A: componentDidUpdate'),
	(338, 85, 'B: componentWillUnmount'),
	(339, 85, 'C: componentDidMount'),
	(340, 85, 'D: render'),
	(341, 86, 'A: To handle routing requests.'),
	(342, 86, 'B: To process incoming requests before they reach the route handler.'),
	(343, 86, 'C: To render HTML templates.'),
	(344, 86, 'D: To connect to a database.'),
	(345, 87, 'A: Using the `route()` method.'),
	(346, 87, 'B: Using the `app.get()`, `app.post()`, etc. methods.'),
	(347, 87, 'C: Using the `defineRoute()` function.'),
	(348, 87, 'D: By creating a new file in the routes directory.'),
	(349, 88, 'A: A package manager for Node.js.'),
	(350, 88, 'B: A JavaScript framework.'),
	(351, 88, 'C: A database management system.'),
	(352, 88, 'D: A web server.'),
	(353, 89, 'A: Using `req.query`.'),
	(354, 89, 'B: Using `req.params`.'),
	(355, 89, 'C: Using `req.body` (requires body-parsing middleware).'),
	(356, 89, 'D: Using `req.data`.'),
	(357, 90, 'A: `res.send(JSON.stringify(data))`'),
	(358, 90, 'B: `res.json(data)`'),
	(359, 90, 'C: `res.render(data)`'),
	(360, 90, 'D: `res.write(data)`'),
	(361, 91, 'A: SQL databases are relational, NoSQL databases are non-relational.'),
	(362, 91, 'B: SQL databases are faster, NoSQL databases are slower.'),
	(363, 91, 'C: SQL databases are only for small datasets, NoSQL databases are for large datasets.'),
	(364, 91, 'D: There is no difference.'),
	(365, 92, 'A: GET'),
	(366, 92, 'B: POST'),
	(367, 92, 'C: PUT'),
	(368, 92, 'D: DELETE'),
	(369, 93, 'A: A tool for managing operating systems.'),
	(370, 93, 'B: A technique for optimizing database queries.'),
	(371, 93, 'C: A library that maps objects to database records, simplifying database interactions in code.'),
	(372, 93, 'D: A type of database.'),
	(373, 94, 'A: Create, Read, Update, Delete'),
	(374, 94, 'B: Connect, Run, Update, Deploy'),
	(375, 94, 'C: Compile, Render, Upload, Download'),
	(376, 94, 'D: Code, Review, Understand, Debug'),
	(377, 95, 'A: 404'),
	(378, 95, 'B: 500'),
	(379, 95, 'C: 200'),
	(380, 95, 'D: 301'),
	(381, 96, 'A. السفر السياحي إلى الخارج'),
	(382, 96, 'B. الدراسة الأكاديمية بدوام كامل في مؤسسة تعليمية معتمدة'),
	(383, 96, 'C. البحث عن عمل بدوام كامل في الخارج'),
	(384, 96, 'D. الإقامة الدائمة في بلد الدراسة'),
	(385, 97, 'A. لأن صديقي نصحني به'),
	(386, 97, 'B. لأنه يبدو سهلاً'),
	(387, 97, 'C. لأنه يتماشى مع اهتماماتي الأكاديمية وأهدافي المهنية'),
	(388, 97, 'D. لأنه البرنامج الدراسي الوحيد المتاح'),
	(389, 98, 'A. لا أعرف بعد'),
	(390, 98, 'B. لا أهتم'),
	(391, 98, 'C. العودة إلى بلدي والمساهمة في تطوير مجال دراستي'),
	(392, 98, 'D. البقاء في بلد الدراسة والبحث عن عمل'),
	(393, 99, 'A. لا أعرف'),
	(394, 99, 'B. المؤسسة التعليمية المجاورة لمنزلي'),
	(395, 99, 'C. [الاسم الصحيح للمؤسسة التعليمية]'),
	(396, 99, 'D. أي مؤسسة تعليمية تقبلني'),
	(397, 100, 'A. لا أعرف'),
	(398, 100, 'B. الدولة المضيفة'),
	(399, 100, 'C. أنا شخصياً/والدي/كفيل آخر'),
	(400, 100, 'D. سأعتمد على المنح الدراسية فقط'),
	(401, 101, 'A. لا أعرف'),
	(402, 101, 'B. مبلغ تقريبي جداً'),
	(403, 101, 'C. [المبلغ الدقيق]'),
	(404, 101, 'D. سأكتشف لاحقاً'),
	(405, 102, 'A. جواز سفري فقط'),
	(406, 102, 'B. شهادة ميلادي'),
	(407, 102, 'C. كشوف حسابات بنكية، خطابات دعم من الكفيل، إثبات دخل'),
	(408, 102, 'D. لا أحتاج إلى أي مستندات'),
	(409, 103, 'A. لا'),
	(410, 103, 'B. لدي فكرة غامضة'),
	(411, 103, 'C. نعم، بحثت في الأمر وأعرف التكاليف التقريبية للإيجار، الطعام، والمواصلات'),
	(412, 103, 'D. سأعتمد على أصدقائي في معرفة التكاليف'),
	(413, 104, 'A. البقاء في الخارج إلى الأبد'),
	(414, 104, 'B. لا أعرف بعد'),
	(415, 104, 'C. العودة إلى بلدي والمساهمة في مجال دراستي'),
	(416, 104, 'D. الزواج من مواطن/مواطنة من بلد الدراسة'),
	(417, 105, 'A. لا يوجد لدي أي روابط'),
	(418, 105, 'B. عائلتي وأصدقائي فقط'),
	(419, 105, 'C. عائلتي، أصدقائي، عملي السابق، ممتلكاتي، والتزاماتي العائلية'),
	(420, 105, 'D. جواز سفري'),
	(421, 106, 'A. لن تساهم في شيء'),
	(422, 106, 'B. ستساعدني في الحصول على وظيفة أفضل في الخارج'),
	(423, 106, 'C. ستمنحني المهارات والمعرفة اللازمة للمساهمة في تطوير مجال دراستي في بلدي'),
	(424, 106, 'D. سأستفيد منها شخصياً فقط'),
	(425, 107, 'A. لا'),
	(426, 107, 'B. نعم، لدي بعض الديون الصغيرة'),
	(427, 107, 'C. نعم، لدي عقارات أو أعمال تجارية أو التزامات مالية أخرى'),
	(428, 107, 'D. هذا ليس من شأنهم'),
	(429, 108, 'A. لأنه بلد جميل'),
	(430, 108, 'B. لأنني أحب ثقافتهم'),
	(431, 108, 'C. لأنه يقدم أفضل البرامج الدراسية في مجال دراستي، ويتميز بجامعات مرموقة، ويوفر فرص عمل جيدة بعد التخرج'),
	(432, 108, 'D. لأن أصدقائي يدرسون هناك'),
	(433, 109, 'A. لا أعرف شيئاً'),
	(434, 109, 'B. سمعت أنها جامعة جيدة'),
	(435, 109, 'C. أعرف تاريخها، برامجها الدراسية المتميزة، وأساتذتها البارزين'),
	(436, 109, 'D. رأيت صورها على الإنترنت'),
	(437, 110, 'A. سأستسلم'),
	(438, 110, 'B. سأقدم طلباً آخر في بلد آخر'),
	(439, 110, 'C. سأحاول فهم سبب الرفض ومعالجته، ثم أقدم طلباً آخر'),
	(440, 110, 'D. سأحمل غضباً على بلد الدراسة'),
	(441, 111, 'A. لا'),
	(442, 111, 'B. نعم، لدي الكثير من الأقارب والأصدقاء'),
	(443, 111, 'C. نعم، لدي بعض الأقارب/الأصدقاء، ولكن تركيزي الرئيسي هو الدراسة'),
	(444, 111, 'D. لا أريد الإجابة على هذا السؤال');

-- Dumping structure for table interviewai.feedback
CREATE TABLE IF NOT EXISTS `feedback` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `course_id` int DEFAULT NULL,
  `message` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table interviewai.feedback: ~0 rows (approximately)
DELETE FROM `feedback`;

-- Dumping structure for table interviewai.generated_courses
CREATE TABLE IF NOT EXISTS `generated_courses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `course_title` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table interviewai.generated_courses: ~0 rows (approximately)
DELETE FROM `generated_courses`;
INSERT INTO `generated_courses` (`id`, `user_id`, `course_title`, `status`, `created_at`) VALUES
	(1, 3, '', 'ACTIVE', '2025-11-04 21:14:48'),
	(2, 3, '', 'ACTIVE', '2025-11-04 21:19:33'),
	(3, 3, 'Java Developer Interview Crash Course - One Day Prep', 'ACTIVE', '2025-11-04 21:23:42'),
	(4, 3, 'C++ Game Developer Interview Prep: Intensive One-Day Crash Course', 'ACTIVE', '2025-11-04 22:51:32'),
	(5, 3, 'Fullstack Developer Interview Prep: Intensive Crash Course', 'ACTIVE', '2025-11-04 23:16:50'),
	(6, 3, 'Full-Stack Developer Interview Blitz: Tomorrow\'s the Day!', 'ACTIVE', '2025-11-04 23:18:56'),
	(7, 3, 'دورة مكثفة للتحضير لمقابلة تأشيرة الطالب (خلال 24 ساعة)', 'ACTIVE', '2025-11-05 15:53:53');

-- Dumping structure for table interviewai.onboarding_data
CREATE TABLE IF NOT EXISTS `onboarding_data` (
  `user_id` int NOT NULL,
  `interview_type` varchar(50) NOT NULL,
  `language` varchar(50) NOT NULL,
  `timeline` varchar(50) NOT NULL,
  `context` text,
  `cv_path` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `onboarding_data_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table interviewai.onboarding_data: ~0 rows (approximately)
DELETE FROM `onboarding_data`;

-- Dumping structure for table interviewai.progress
CREATE TABLE IF NOT EXISTS `progress` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `course_id` int NOT NULL,
  `xp` int DEFAULT '0',
  `last_updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `course_id` (`course_id`),
  CONSTRAINT `progress_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `progress_ibfk_2` FOREIGN KEY (`course_id`) REFERENCES `courses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table interviewai.progress: ~0 rows (approximately)
DELETE FROM `progress`;

-- Dumping structure for table interviewai.questions
CREATE TABLE IF NOT EXISTS `questions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `chapter_id` int NOT NULL,
  `question` text,
  `question_type` varchar(50) DEFAULT 'MULTIPLE_CHOICE',
  `correct_answer` varchar(255) DEFAULT NULL,
  `explanation` text,
  PRIMARY KEY (`id`),
  KEY `chapter_id` (`chapter_id`),
  CONSTRAINT `questions_ibfk_1` FOREIGN KEY (`chapter_id`) REFERENCES `chapters` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=112 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table interviewai.questions: ~0 rows (approximately)
DELETE FROM `questions`;
INSERT INTO `questions` (`id`, `chapter_id`, `question`, `correct_answer`, `explanation`) VALUES
	(1, 1, 'Which of the following is NOT a fundamental principle of Object-Oriented Programming (OOP)?', 'C. Compilation', 'Compilation is a process of translating source code into machine code, while Encapsulation, Polymorphism, and Inheritance are core OOP principles.'),
	(2, 1, 'What is the purpose of the \'final\' keyword in Java when applied to a class?', 'C. It prevents the class from being subclassed', 'When a class is declared as \'final\', it cannot be extended (subclassed) by any other class. This provides immutability at the class level.'),
	(3, 1, 'Which of the following is the correct way to create an instance of a class named \'MyClass\'?', 'C. new MyClass()', 'The \'new\' keyword is used in Java to create a new instance (object) of a class. It calls the class\'s constructor.'),
	(4, 1, 'What is the difference between \'==\' and \'.equals()\' in Java when comparing objects?', 'B. \'==\' compares memory addresses, while \'.equals()\' compares object content (default behavior)', '\'==\' checks if two object references point to the same memory location (the same object instance). \'.equals()\' (by default in Object class) also compares memory addresses, but it can be overridden in a class to compare the content of the objects.  Important to remember that many classes override the equals() method such as String.'),
	(5, 1, 'What is the purpose of the `static` keyword in Java?', 'C. To associate a variable or method with the class rather than an instance of the class', 'The `static` keyword makes a variable or method belong to the class itself, not to any specific object instance. This means that there\'s only one copy of the static variable shared among all objects of the class.'),
	(6, 2, 'Which data structure is best suited for implementing a Last-In-First-Out (LIFO) behavior?', 'C. Stack', 'A stack follows the LIFO principle, where the last element added is the first one to be removed.'),
	(7, 2, 'Which of the following interfaces does NOT extend the Collection interface?', 'C. Map', 'The Map interface represents a key-value pair structure and is not a direct subtype of the Collection interface.  Lists, Sets, and Queues are all subtypes of Collection.'),
	(8, 2, 'Which of the following implementations of the List interface provides the best performance for random access (getting an element by its index)?', 'B. ArrayList', 'ArrayLists use an underlying array, providing O(1) time complexity for accessing elements by index. LinkedLists have O(n) complexity for random access.'),
	(9, 2, 'What is the purpose of the \'hashCode()\' method in Java?', 'C. To provide a hash code value for an object, which is used by hash-based collections like HashMap and HashSet', 'The hashCode() method is used by hash-based collections to efficiently store and retrieve objects. It should be consistent with the equals() method.'),
	(10, 2, 'Which collection guarantees the order of elements as they were inserted?', 'C. LinkedHashSet', 'LinkedHashSet maintains the insertion order of elements, unlike HashSet which does not guarantee any specific order, or TreeSet which maintains sorted order. PriorityQueue orders elements based on priority.'),
	(11, 3, 'Which keyword is used to explicitly throw an exception in Java?', 'C. throw', 'The \'throw\' keyword is used to create a new exception object and throw it, interrupting the normal flow of execution.'),
	(12, 3, 'What is the purpose of the \'finally\' block in a try-catch block?', 'C. To execute code regardless of whether an exception occurs or not', 'The \'finally\' block guarantees that the code within it will be executed, whether an exception is thrown and caught or not. It is commonly used for resource cleanup.'),
	(13, 3, 'Which of the following is NOT a valid state of a thread in Java?', 'D. Compiled', 'The valid states of a thread include Running, Blocked (Waiting/Sleeping), Ready (Runnable), New, and Terminated. Compiled is not a state of a Thread.'),
	(14, 3, 'What is the purpose of the \'synchronized\' keyword in Java?', 'B. To ensure that only one thread can access a specific block of code or method at a time', 'The \'synchronized\' keyword provides a mechanism for thread synchronization, preventing race conditions and ensuring data consistency in multithreaded environments.'),
	(15, 3, 'What is a deadlock in the context of multithreading?', 'B. A situation where two or more threads are blocked indefinitely, waiting for each other to release resources', 'Deadlock occurs when threads are stuck in a circular waiting pattern, preventing any of them from progressing. For example, Thread A holds lock 1 and waits for lock 2, while Thread B holds lock 2 and waits for lock 1.'),
	(16, 4, 'Which class is commonly used to read character-based data from a file in Java?', 'C. BufferedReader', 'BufferedReader is designed for efficient reading of character-based data from an input stream, typically a file. FileInputStream is for byte-based data.'),
	(17, 4, 'Which design pattern ensures that a class has only one instance and provides a global point of access to it?', 'B. Singleton', 'The Singleton pattern restricts the instantiation of a class to a single object.'),
	(18, 4, 'Which of the following classes is used to create a socket connection in Java?', 'B. Socket', 'The Socket class represents one endpoint of a two-way communication link between two programs running on the network. ServerSocket is used on the server-side to listen for incoming connections.'),
	(19, 4, 'What is the purpose of the Factory design pattern?', 'B. To encapsulate object creation logic', 'The Factory pattern provides an interface for creating objects without specifying their concrete classes, thereby decoupling the client from the specific object instantiation process.'),
	(20, 4, 'Which interface is at the root of the hierarchy when using Java I/O to write data?', 'C. OutputStream', 'OutputStream and its derived classes (like FileOutputStream, BufferedOutputStream) are used for writing binary/byte data.  Writer and its derived classes (like FileWriter, BufferedWriter) are used for writing character data. InputStream and Reader are for *reading* data.'),
	(21, 5, 'In which memory area does the JVM store object instances?', 'B. Heap', 'The heap is the runtime data area from which memory for all class instances and arrays is allocated. It\'s where objects live.'),
	(22, 5, 'What is the main purpose of garbage collection in Java?', 'B. To reclaim memory occupied by unused objects', 'Garbage collection automatically reclaims memory that is no longer being used by the application, preventing memory leaks.'),
	(23, 5, 'Which generation in the JVM heap typically contains newly created objects?', 'C. Young Generation', 'Newly created objects are initially placed in the Young Generation (specifically, in the Eden space). Then if objects survive several GC cycles they can be moved to old generation. Permanent generation/Metaspace stores class metadata and other information and the code cache is used for storing compiled code.'),
	(24, 5, 'Which of the following is NOT a type of Garbage Collector algorithm in Java?', 'D. Quantum Garbage Collector', 'Serial, Parallel, and CMS are valid garbage collection algorithms. Quantum Garbage Collector is not a recognized term in Java garbage collection.'),
	(25, 5, 'What is the role of the `finalize()` method in Java?', 'B. To release resources held by an object before it\'s garbage collected', 'The `finalize()` method is called by the garbage collector on an object when garbage collection determines that there are no more references to the object. It allows the object to clean up resources it held.'),
	(26, 6, 'Which of the following is the correct way to dynamically allocate an array of 10 integers in C++?', 'B. int* arr = new int[10];', 'This uses the \'new\' operator to allocate memory on the heap for an array of 10 integers and assigns the pointer to the first element to \'arr\'.'),
	(27, 6, 'What is a smart pointer in C++ and why is it useful?', 'C. A pointer that automatically manages the lifetime of dynamically allocated objects, preventing memory leaks.', 'Smart pointers (like `std::unique_ptr`, `std::shared_ptr`) handle the deallocation of memory when the pointer goes out of scope, preventing memory leaks. They are crucial for RAII (Resource Acquisition Is Initialization).'),
	(28, 6, 'Which of the following is NOT a core principle of Object-Oriented Programming (OOP)?', 'D. Recursion', 'Recursion is a programming technique where a function calls itself. While useful, it is not one of the core OOP principles. The others, Inheritance, Polymorphism, and Encapsulation, are fundamental to OOP.'),
	(29, 6, 'What is the purpose of the \'const\' keyword in C++?', 'C. To indicate that a variable or function parameter cannot be modified.', 'The `const` keyword signifies that a variable or function parameter is read-only and cannot be changed after initialization or within the scope where it\'s declared `const`.'),
	(30, 6, 'What is the difference between \'malloc\' and \'new\' in C++?', 'B. \'new\' allocates memory and calls the constructor of the object, while \'malloc\' only allocates raw memory.', '\'new\' is a C++ operator that not only allocates memory but also calls the constructor of the object being created. \'malloc\' (from C) only allocates raw, uninitialized memory and requires casting, and doesn\'t call constructors.'),
	(31, 7, 'What is the purpose of the game loop in a game engine?', 'C. To update the game state and render the graphics repeatedly.', 'The game loop is the core of a game engine. It continuously updates the game state (physics, AI, etc.) and then renders the scene to the screen, creating the illusion of animation and interactivity.'),
	(32, 7, 'Which design pattern is best suited for decoupling the game\'s data (Model) from its presentation (View) and user interaction (Controller)?', 'D. Model-View-Controller (MVC)', 'MVC is specifically designed to separate concerns and improve the maintainability and testability of an application. It clearly divides data, presentation, and user input handling.'),
	(33, 7, 'What is a scene graph?', 'B. A hierarchical data structure representing the spatial relationships between game objects in a scene.', 'A scene graph allows for efficient rendering and manipulation of objects in a game world by organizing them in a tree-like structure based on their spatial relationships. This allows for operations like scaling or translation to be applied to entire branches of the graph.'),
	(34, 7, 'What is the purpose of a shader in the rendering pipeline?', 'C. To perform calculations on vertices and pixels to determine the final rendered image.', 'Shaders are small programs that run on the GPU and are responsible for tasks like vertex transformations, lighting calculations, and texture mapping. They are a crucial part of the modern rendering pipeline.'),
	(35, 7, 'Which design pattern defines a one-to-many dependency between objects so that when one object changes state, all its dependents are notified and updated automatically?', 'B. Observer', 'The Observer pattern is used to implement distributed event handling systems.  The \'subject\' (the object being observed) maintains a list of \'observers\' and notifies them of any state changes, typically by calling one of their methods.'),
	(36, 8, 'What is a vector dot product used for?', 'D. To calculate the component of one vector in the direction of another.', 'The dot product of two vectors gives a scalar value that is proportional to the cosine of the angle between them. It is commonly used to project one vector onto another, determining how much of one vector points in the same direction as the other. It also can determine if two vectors are perpendicular (dot product is 0) or nearly so.'),
	(37, 8, 'Which matrix is used to rotate a 3D object around the Y-axis?', 'C. Rotation matrix', 'Rotation matrices are used to rotate objects around a specific axis. Applying a rotation matrix to a vector will change the direction of the vector, effectively rotating the object the vector represents.'),
	(38, 8, 'What is a quaternion, and why are they used in game development?', 'B. A four-dimensional number system used to represent rotations, avoiding gimbal lock.', 'Quaternions are a mathematical construct used to represent rotations in 3D space. They are preferred over Euler angles because they avoid the problem of gimbal lock, which can cause unexpected and uncontrollable rotations.'),
	(39, 8, 'What does the cross product of two vectors result in?', 'B. A vector perpendicular to both input vectors.', 'The cross product of two vectors produces a new vector that is orthogonal (perpendicular) to both of the original vectors.  The magnitude of the resulting vector is equal to the area of the parallelogram formed by the two original vectors.'),
	(40, 8, 'What is the purpose of a transformation matrix in game development?', 'C. To represent the position, rotation, and scale of a game object in world space.', 'A transformation matrix is a single matrix that combines the translation, rotation, and scaling operations of an object. Applying this matrix to a vertex of the object will transform it from object space to world space.'),
	(41, 9, 'Which data structure is most efficient for searching for a specific element by its key, assuming the keys are uniformly distributed?', 'C. Hash Table', 'Hash tables provide average-case O(1) (constant time) lookup, making them the most efficient for searching by key, assuming a good hash function and minimal collisions. Other options have O(log n) or O(n) complexities.'),
	(42, 9, 'Which sorting algorithm has the best average-case time complexity?', 'C. Merge Sort', 'Merge Sort has an average and worst-case time complexity of O(n log n), which is more efficient than the O(n^2) complexity of Bubble Sort, Insertion Sort, and Selection Sort.'),
	(43, 9, 'What is the A* algorithm primarily used for?', 'B. Pathfinding', 'A* is a widely used pathfinding algorithm that efficiently finds the shortest path between two points by using a heuristic to estimate the cost of reaching the goal from any given node.'),
	(44, 9, 'What is the time complexity to access an element in an array?', 'C. O(1)', 'Accessing an element in an array by its index takes constant time, O(1), because the memory address of the element can be calculated directly from the index and the starting address of the array.'),
	(45, 9, 'Which data structure follows the Last-In, First-Out (LIFO) principle?', 'C. Stack', 'A stack is a data structure that operates on the LIFO principle, meaning the last element added to the stack is the first one removed. This is commonly implemented using operations like push (add to the top) and pop (remove from the top).'),
	(46, 10, 'Which C++ library is commonly used for creating GUIs (Graphical User Interfaces) in game development?', 'C. Qt', 'Qt is a cross-platform application development framework that is often used for creating GUIs in C++ game development. It provides a comprehensive set of tools and widgets for designing user interfaces.'),
	(47, 10, 'What is the purpose of the Entity-Component-System (ECS) architecture in game development?', 'B. To organize game entities and their data in a modular and flexible way.', 'ECS is an architectural pattern that promotes composition over inheritance. Entities are containers for components (data), and systems operate on entities based on their components. This provides flexibility and avoids the tight coupling of traditional OOP.'),
	(48, 10, 'What is the difference between immediate mode GUI and retained mode GUI?', 'B. Retained mode GUIs are rendered only once and persist on screen, while immediate mode GUIs are re-rendered every frame.', 'Immediate mode GUIs are re-rendered every frame. They are easy to use and often used for debug tools and prototyping. Retained mode GUIs persist between frames which can improve rendering times.'),
	(49, 10, 'Which C++ feature allows you to create a single function or class that can work with different data types?', 'C. Templates', 'Templates allow you to write generic code that can work with different data types without having to rewrite the code for each type. This is a powerful feature for creating reusable and efficient code in game development.'),
	(50, 10, 'What is the benefit of using a profiler in game development?', 'C. To identify performance bottlenecks and areas where the code can be optimized.', 'A profiler is a tool that measures the execution time of different parts of the code, allowing developers to identify areas where the code is slow or inefficient. This information can then be used to optimize the code and improve the game\'s performance.'),
	(51, 11, 'Which of the following is the correct way to declare a constant variable in JavaScript?', 'B: const myConst = 10;', 'The `const` keyword is used to declare a constant variable, meaning its value cannot be reassigned after initialization.'),
	(52, 11, 'What is the purpose of the `async` keyword in JavaScript?', 'C: To make a function return a Promise.', 'The `async` keyword allows you to use `await` within a function and implicitly returns a Promise. If the function returns a value directly, that value is wrapped in a resolved Promise.'),
	(53, 11, 'Which method is used to add an element to the end of an array in JavaScript?', 'B: array.push()', 'The `push()` method adds one or more elements to the end of an array and returns the new length of the array.'),
	(54, 11, 'What is the difference between `==` and `===` in JavaScript?', 'B: `==` compares only values, `===` compares values and types.', '`==` performs type coercion before comparison, while `===` performs strict equality comparison without type coercion. It\'s generally recommended to use `===` to avoid unexpected behavior.'),
	(55, 11, 'Which of the following is a valid way to handle errors in a Promise?', 'C: `promise.then(null, error => { ... });`', 'While `promise.catch(error => { ... });` is the more common and readable approach, it\'s technically syntactic sugar for `promise.then(null, error => { ... });`. Options A and B are incorrect syntax.'),
	(56, 12, 'What is JSX in React?', 'B: A JavaScript extension that allows writing HTML-like syntax in JavaScript.', 'JSX allows you to write HTML-like structures within your JavaScript code, making it easier to create and manage React components.  It\'s transpiled into standard JavaScript by tools like Babel.'),
	(57, 12, 'Which of the following is the correct way to update the state in a React class component?', 'C: `this.setState({ name: \'New Name\' });`', 'The `setState()` method is the correct way to update the state of a React component. It triggers a re-render of the component.'),
	(58, 12, 'What is a React Hook?', 'B: A way to use state and other React features in functional components.', 'Hooks like `useState` and `useEffect` allow you to use state and lifecycle features in functional components, making them more powerful and concise.'),
	(59, 12, 'What is the purpose of the `useEffect` Hook in React?', 'A: To create side effects in functional components.', '`useEffect` allows you to perform side effects like data fetching, DOM manipulation, or subscriptions after the component renders.'),
	(60, 12, 'What is the purpose of keys in React lists?', 'B: To uniquely identify list items, improving performance and preventing unexpected behavior.', 'Keys help React efficiently update the DOM when list items are added, removed, or reordered.'),
	(61, 13, 'What is Node.js?', 'B: A JavaScript runtime environment that executes JavaScript code outside of a web browser.', 'Node.js allows you to run JavaScript on the server-side, enabling full-stack development using a single language.'),
	(62, 13, 'What is Express.js?', 'B: A Node.js web application framework that provides a robust set of features for web and mobile applications.', 'Express.js simplifies the process of building web applications and APIs with Node.js, providing features like routing, middleware, and templating.'),
	(63, 13, 'What is middleware in Express.js?', 'B: A function that has access to the request object (req), the response object (res), and the next middleware function in the application’s request-response cycle.', 'Middleware functions can perform tasks like logging, authentication, and request body parsing before or after the route handler.'),
	(64, 13, 'Which HTTP method is typically used to retrieve data from a server?', 'D: GET', 'The GET method is used to request data from a specified resource. It\'s considered a safe method because it doesn\'t modify the server\'s state.'),
	(65, 13, 'What does REST stand for?', 'A: Representational State Transfer', 'REST is an architectural style for designing networked applications. It relies on stateless communication and well-defined resources.'),
	(66, 14, 'Which of the following is a NoSQL database?', 'C: MongoDB', 'MongoDB is a document-oriented NoSQL database that stores data in JSON-like documents.'),
	(67, 14, 'Which SQL keyword is used to retrieve data from a database table?', 'D: SELECT', 'The SELECT statement is used to retrieve data from one or more tables in a database.'),
	(68, 14, 'What is the purpose of an ORM (Object-Relational Mapper)?', 'B: To provide a way to interact with a database using object-oriented programming concepts.', 'ORMs like Sequelize or Mongoose allow you to interact with databases using objects and models, abstracting away the complexities of writing raw SQL queries.'),
	(69, 14, 'What does CRUD stand for in database operations?', 'A: Create, Read, Update, Delete', 'CRUD operations represent the fundamental actions performed on data in a database.'),
	(70, 14, 'Which of the following is a characteristic of a relational database?', 'C: Data is organized into tables with rows and columns', 'Relational databases use a structured schema to organize data into tables, enforcing relationships and data integrity.'),
	(71, 15, 'What is horizontal scaling?', 'B: Adding more servers to a system.', 'Horizontal scaling involves distributing the workload across multiple machines, improving scalability and resilience.'),
	(72, 15, 'What is the purpose of a load balancer?', 'B: To distribute network traffic across multiple servers.', 'Load balancers improve performance, availability, and reliability by distributing traffic evenly across multiple servers, preventing any single server from being overwhelmed.'),
	(73, 15, 'What is caching?', 'A: Storing frequently accessed data in a faster storage medium.', 'Caching reduces latency and improves performance by storing frequently accessed data in memory or other fast storage, allowing for quicker retrieval.'),
	(74, 15, 'Which of the following is a benefit of using microservices architecture?', 'B: Faster development cycles and independent deployments.', 'Microservices allow teams to work independently on different services, leading to faster development and deployment cycles. Each service can be deployed and scaled independently.'),
	(75, 15, 'What is the CAP theorem?', 'A: A theorem about the relationship between Consistency, Availability, and Partition Tolerance in distributed systems.', 'The CAP theorem states that in a distributed system, you can only guarantee two out of the three properties: Consistency, Availability, and Partition Tolerance.'),
	(76, 16, 'What is the difference between `==` and `===` in JavaScript?', 'A: `==` compares values, `===` compares values and types.', '`==` performs type coercion before comparison if the operands are of different types. `===` does not perform type coercion and returns true only if both operands have the same value and the same type.'),
	(77, 16, 'What is a closure in JavaScript?', 'A: A function that has access to the parent scope, even after the parent function has closed.', 'A closure allows a function to access variables from its outer scope, even after the outer function has finished executing. This is a powerful concept for data encapsulation and state management.'),
	(78, 16, 'How do you prevent the default behavior of an HTML element\'s event?', 'A: Use the `preventDefault()` method on the event object.', 'The `preventDefault()` method is used to stop the browser from performing its default action associated with the event, such as submitting a form or navigating to a link.'),
	(79, 16, 'What is event bubbling in the DOM?', 'B: The process of an event being triggered on an element and then propagating up the DOM tree to its parent elements.', 'Event bubbling means that when an event occurs on an element, it will first run the handlers on that element, then propagate up the DOM tree, triggering handlers on parent elements as well.'),
	(80, 16, 'Which of the following is NOT a valid JavaScript data type?', 'D: Float', 'While JavaScript uses floating-point numbers, it doesn\'t have a specific \'Float\' data type. It uses \'Number\' to represent both integers and floating-point values.'),
	(81, 17, 'What is JSX in React?', 'A: A JavaScript extension that allows writing HTML-like syntax in JavaScript.', 'JSX (JavaScript XML) allows developers to write HTML-like structures within JavaScript code, making it easier to define UI elements in React.  It gets transpiled to standard JavaScript function calls.'),
	(82, 17, 'What is the purpose of `useState` hook in React?', 'A: To manage the state of a functional component.', 'The `useState` hook allows functional components to have state variables that can be updated, triggering re-renders of the component.'),
	(83, 17, 'How do you pass data from a parent component to a child component in React?', 'A: Using `props`.', 'Props (short for properties) are used to pass data from a parent component to a child component. They are read-only from the child\'s perspective.'),
	(84, 17, 'What does the `useEffect` hook do in React?', 'A: It performs side effects in functional components, like data fetching or DOM manipulation.', '`useEffect` allows you to perform side effects in your functional components. It\'s commonly used for tasks like fetching data from an API, setting up subscriptions, or directly manipulating the DOM.'),
	(85, 17, 'Which lifecycle method is invoked only once during the component\'s entire lifecycle?', 'C: componentDidMount', '`componentDidMount` is invoked immediately after a component is mounted (inserted into the tree). It is used to perform initial setup such as data fetching, setting up subscriptions, or directly manipulating the DOM.'),
	(86, 18, 'What is the purpose of `middleware` in Express.js?', 'B: To process incoming requests before they reach the route handler.', 'Middleware functions have access to the request object (req), the response object (res), and the next middleware function in the application\'s request-response cycle. They can modify the request or response objects, end the request-response cycle, or call the next middleware function.'),
	(87, 18, 'How do you define a route in Express.js?', 'B: Using the `app.get()`, `app.post()`, etc. methods.', 'Express.js provides methods like `app.get()`, `app.post()`, `app.put()`, `app.delete()`, etc., to define routes for different HTTP methods.  These methods take a path and a callback function (the route handler).'),
	(88, 18, 'What is the purpose of `npm`?', 'A: A package manager for Node.js.', 'npm (Node Package Manager) is a command-line tool used for installing, updating, and managing dependencies in Node.js projects. It simplifies the process of using third-party libraries and modules.'),
	(89, 18, 'How do you access request body data in Express.js?', 'C: Using `req.body` (requires body-parsing middleware).', 'The request body data (e.g., from a POST request) is available in the `req.body` property. However, you typically need to use middleware like `body-parser` or the built-in Express middleware `express.json()` or `express.urlencoded()` to parse the request body first.'),
	(90, 18, 'Which of the following is the correct way to send a JSON response in Express.js?', 'B: `res.json(data)`', '`res.json(data)` automatically sets the Content-Type header to application/json and sends the JSON representation of the data to the client.'),
	(91, 19, 'What is the difference between SQL and NoSQL databases?', 'A: SQL databases are relational, NoSQL databases are non-relational.', 'SQL databases use a relational model with structured data and schemas. NoSQL databases use various data models (document, key-value, graph) and are generally more flexible and scalable but can have weaker consistency guarantees.'),
	(92, 19, 'Which HTTP method is typically used to update an existing resource in a RESTful API?', 'C: PUT', 'PUT is typically used to replace an existing resource entirely. PATCH is used for partial updates. POST is used to create new resources or perform actions.'),
	(93, 19, 'What is an ORM (Object-Relational Mapper)?', 'C: A library that maps objects to database records, simplifying database interactions in code.', 'An ORM allows you to interact with a database using object-oriented concepts, abstracting away the complexities of writing raw SQL queries. Popular ORMs include Sequelize (for Node.js) and Django ORM (for Python).'),
	(94, 19, 'What does the acronym CRUD stand for?', 'A: Create, Read, Update, Delete', 'CRUD represents the four basic operations performed on persistent data: creating new data, reading existing data, updating existing data, and deleting data.'),
	(95, 19, 'Which HTTP status code indicates a successful request?', 'C: 200', '200 OK signifies that the request has succeeded. 404 means resource not found, 500 means internal server error, and 301 means the resource has been permanently moved.'),
	(96, 20, 'ما هو الغرض الرئيسي من الحصول على تأشيرة طالب؟', 'B', 'الغرض الرئيسي من تأشيرة الطالب هو السماح لك بالدراسة الأكاديمية بدوام كامل في مؤسسة تعليمية معتمدة في بلد الدراسة.'),
	(97, 20, 'لماذا اخترت هذا البرنامج الدراسي بالتحديد؟', 'C', 'يجب أن يكون لديك سبب واضح ومحدد لاختيار هذا البرنامج الدراسي، وأن تكون قادراً على شرح كيف يتماشى مع اهتماماتك وأهدافك.'),
	(98, 20, 'ما هي أهدافك المهنية بعد الانتهاء من هذا البرنامج الدراسي؟', 'C', 'يجب أن يكون لديك خطة واضحة لما تنوي القيام به بعد الانتهاء من دراستك، وأن تكون قادراً على شرح كيف سيساعدك هذا البرنامج في تحقيق أهدافك.'),
	(99, 20, 'ما هو اسم الجامعة أو المؤسسة التعليمية التي ستدرس فيها؟', 'C', 'يجب أن تعرف اسم المؤسسة التعليمية التي ستدرس فيها وأن تكون قادراً على تهجئته بشكل صحيح.'),
	(100, 21, 'من سيتحمل تكاليف دراستك وإقامتك في الخارج؟', 'C', 'يجب أن يكون لديك مصدر واضح للتمويل وأن تكون قادراً على تقديم دليل على ذلك.'),
	(101, 21, 'ما هو المبلغ الإجمالي الذي سيتم تخصيصه لتغطية تكاليف الدراسة والمعيشة خلال فترة دراستك؟', 'C', 'يجب أن يكون لديك تقدير دقيق لتكاليف الدراسة والمعيشة وأن تكون قادراً على إظهار أن لديك ما يكفي من المال لتغطيتها.'),
	(102, 21, 'ما هي أنواع المستندات التي تثبت قدرتك المالية؟', 'C', 'عادة ما تكون كشوف الحسابات البنكية، وخطابات الدعم من الكفيل، وإثبات الدخل هي المستندات المطلوبة لإثبات قدرتك المالية.'),
	(103, 21, 'هل أنت على علم بتكاليف المعيشة التقريبية في المدينة التي ستدرس فيها؟', 'C', 'إظهار معرفتك بتكاليف المعيشة يدل على أنك مستعد جيداً للدراسة في الخارج.'),
	(104, 22, 'ما هي خططك بعد الانتهاء من دراستك؟', 'C', 'من المهم أن تعبر عن نيتك في العودة إلى بلدك والمساهمة فيه بعد الانتهاء من دراستك.'),
	(105, 22, 'ما هي الروابط التي تربطك ببلدك الأم؟', 'C', 'يجب أن تكون قادراً على إظهار الروابط القوية التي تربطك ببلدك، مثل العائلة، الأصدقاء، العمل، والممتلكات.'),
	(106, 22, 'كيف ستساهم دراستك في الخارج في تطوير بلدك؟', 'C', 'يجب أن تكون قادراً على شرح كيف ستساعدك دراستك في الخارج في تطوير مهاراتك ومعرفتك للمساهمة في تطوير بلدك.'),
	(107, 22, 'هل لديك أي ممتلكات أو التزامات مالية في بلدك الأم؟', 'C', 'وجود ممتلكات أو التزامات مالية في بلدك الأم يعزز فكرة نيتك في العودة.'),
	(108, 23, 'لماذا اخترت الدراسة في [اسم بلد الدراسة]؟', 'C', 'يجب أن تركز على الأسباب الأكاديمية والمهنية لاختيارك بلد الدراسة.'),
	(109, 23, 'ماذا تعرف عن الجامعة التي ستدرس فيها؟', 'C', 'يجب أن تكون على دراية بالمعلومات الأساسية عن الجامعة التي ستدرس فيها.'),
	(110, 23, 'ماذا ستفعل إذا تم رفض طلب التأشيرة الخاص بك؟', 'C', 'إظهار أنك ستتعامل مع الرفض بشكل بناء يدل على جديتك في الحصول على التأشيرة.'),
	(111, 23, 'هل لديك أي أقارب أو أصدقاء يقيمون في [اسم بلد الدراسة]؟', 'C', 'من الأفضل أن تكون صريحاً، ولكن أكد أن تركيزك الرئيسي هو الدراسة وليس الزيارة أو الإقامة مع الأقارب/الأصدقاء.');

-- Dumping structure for table interviewai.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `role` varchar(20) DEFAULT 'CANDIDATE',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table interviewai.users: ~3 rows (approximately)
DELETE FROM `users`;
INSERT INTO `users` (`id`, `username`, `email`, `password_hash`, `created_at`, `role`) VALUES
	(1, 'test', 'test@gmail.com', '$2a$10$1tIGyVdtnKHBM4WnPMy5Ve3Q/lBaMhgnOmELWRWpuJXyxT5g4UfqS', '2025-11-01 14:15:02', 'CANDIDATE'),
	(2, 'testtest', 'test@test.com', '$2a$10$sdQhCBtbEgQdmxPG1TsN1uAGXRLxCmRFPyLk1AKTYUkOigeoEwoHK', '2025-11-02 14:24:10', 'CANDIDATE'),
	(3, 'fahd', 'fahd@gmail.com', '$2a$10$fcvTx/HDUJskkBdMW5RVQukRbyt04SaNeIujUNr0NHcB4Kjt2cBce', '2025-11-02 17:17:00', 'CANDIDATE'),
	(4, 'hassan', 'hassan@gmail.com', '$2a$10$ZA/1jxV6zhkgECQl99EEAeX88S/V24c6P1zIuzQhwpLrLlalqGrge', '2025-11-05 15:18:55', 'CANDIDATE');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
